models/Posts.php
<?php

namespace app\models;

use Yii;
use yii\db\pgsql\QueryBuilder;
use yii\db\Query;

/**
 * Esta es una clase modelo para la tabla "posts".
 *
 * @property int $id
 * @property string $titulo
 * @property string $created_at
 * @property string $media
 * @property string $desarrollo
 * @property int $juego_id
 * @property int $usuario_id
 *
 * @property Comentarios[] $comentarios
 * @property Juegos $juego
 * @property Usuarios $usuario
 */
class Posts extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'posts';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['titulo', 'juego_id', 'usuario_id'], 'required'],
            [['created_at'], 'safe'],
            [['desarrollo'], 'string'],
            [['juego_id', 'usuario_id'], 'default', 'value' => null],
            [['juego_id', 'usuario_id'], 'integer'],
            [['titulo', 'media'], 'string', 'max' => 255],
            [['juego_id'], 'exist', 'skipOnError' => true, 'targetClass' => Juegos::className(), 'targetAttribute' => ['juego_id' => 'id']],
            [['usuario_id'], 'exist', 'skipOnError' => true, 'targetClass' => Usuarios::className(), 'targetAttribute' => ['usuario_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'titulo' => 'Titulo',
            'created_at' => 'Created At',
            'media' => 'Media',
            'desarrollo' => 'Desarrollo',
            'juego_id' => 'Juego ID',
            'usuario_id' => 'Usuario ID',
        ];
    }

    /**
     * Devuelve query para [[Comentarios]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getComentarios()
    {
        return $this->hasMany(Comentarios::className(), ['post_id' => 'id'])->inverseOf('post');
    }

    /**
     * Devuelve el juego asociado al post
     *
     * @return Juegos
     */
    public function getJuego()
    {
        return $this->hasOne(Juegos::className(), ['id' => 'juego_id'])->inverseOf('posts');
    }

    /**
     * Devuelve el usuario asociado al post
     *
     * @return Usuarios
     */
    public function getUsuario()
    {
        return $this->hasOne(Usuarios::className(), ['id' => 'usuario_id'])->inverseOf('posts');
    }

    /**
     * Devuelve el numero del total de votos del post
     *
     * @return integer
     */
    public function getVotos()
    {
        return VotosPosts::find()->where(['post_id' => $this->id])->count();
    }

    /**
     * Devuelve si el usuario ha votado el post o no
     *
     * @param [integer] $uId el id del usuario que estamos comprobando
     * @return boolean si ha votado el post o no
     */
    public function usuarioVotado($uId)
    {
        return VotosPosts::find()->where(['post_id' => $this->id, 'usuario_id' => $uId])->exists();
    }
}

controllers/PostsController.php
<?php

namespace app\controllers;

use app\models\Comentarios;
use app\models\Juegos;
use app\models\Posts;
use app\models\PostsSearch;
use app\models\VotosPosts;
use Yii;
use yii\data\ActiveDataProvider;
use yii\db\Query;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * PostsController implementa las acciones CRUD para el modelo Posts.
 */
class PostsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['create', 'update', 'delete', 'votar'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['create'],
                        'roles' => ['@'],
                    ],
                    [
                        'allow' => true,
                        'actions' => ['update', 'delete'],
                        'matchCallback' => function ($rule, $action) {
                            $model = $this->findModel(Yii::$app->request->queryParams['id']);
                            if (!Yii::$app->user->isGuest && ($model->usuario->id == Yii::$app->user->id)) {
                                return true;
                            }
                            Yii::$app->session->setFlash('error', '¡No puedes modificar el post de otra persona!');
                            return false;
                        },
                    ],
                    [
                        'allow' => true,
                        'actions' => ['votar'],
                        'matchCallback' => function ($rule, $action) {
                            if (Yii::$app->user->isGuest) {
                                Yii::$app->session->setFlash('error', '¡No puedes votar sin iniciar sesion!');
                                return false;
                            }

                            return true;
                        },
                    ],
                ],
            ],
        ];
    }

    /**
     * Lista todos los modelos Posts.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new PostsSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Muestra un único modelo Posts.
     *
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException si el modelo no se encuentra
     */
    public function actionView($id)
    {
        $usuarioVotado = Yii::$app->user->isGuest ? false : $this->findModel($id)->usuarioVotado(Yii::$app->user->id);

        $queryComentarios = Comentarios::find()->where(['post_id' => $id]);

        $comentariosProvider = new ActiveDataProvider([
            'query' => $queryComentarios,
        ]);

        return $this->render('view', [
            'model' => $this->findModel($id),
            'usuarioHaVotado' => $usuarioVotado,
            'comentariosProvider' => $comentariosProvider,
        ]);
    }

    /**
     * Crea un nuevo modelo Posts.
     * Si la creacion es exitosa, redirecciona a la pagina de vista.
     * Esta accion esta limitada solo a los usuarios logueados.
     *
     * @return Response|string
     */
    public function actionCreate()
    {
        $model = new Posts();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('create', [
            'model' => $model,
            'listaJuegos' => Juegos::listaAsociativa(),
        ]);
    }

    /**
     * Actualiza un modelo Posts.
     * Si se actualiza con éxito, redireciona a la pagina de vista del modelo.
     * Esta accion esta limitada solo al usuario creador del post.
     *
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException si el modelo no se encuentra
     * @throws ForbiddenHttpException si el usuario logueado no es el propietario
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
            'listaJuegos' => Juegos::listaAsociativa(),
        ]);
    }

    /**
     * Borra un modelo Posts.
     * Si el borrado es exitoso, redirecciona a la pagina indice
     * Esta accion esta limitada solo al usuario creador del post.
     *
     * @param int $id
     * @return mixed
     * @throws NotFoundHttpException si el modelo no se encuentra
     * @throws ForbiddenHttpException si el usuario logueado no es el propietario
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Encuentra el modelo Posts basado en su clave primaria.
     * Si el modelo no se encuentra, una excepcion HTTP 404 se lanzará.
     *
     * @param int $id
     * @return Posts el modelo cargado
     * @throws NotFoundHttpException si el modelo no se encuentra
     */
    protected function findModel($id)
    {
        if (($model = Posts::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('La pagina solicitada no existe');
    }
    
    /**
     * Funcion para votar posts
     * Esta accion esta limitada solo a los usuarios logueados
     *
     * @return integer el numero de votos total despues de votar el post
     * @throws ForbiddenHttpException si el usuario no esta logueado
     */
    public function actionVotar()
    {
        $requestPost = Yii::$app->request->post();
        $uId = $requestPost['uId'];
        $pId = $requestPost['pId'];
        

        $voto = VotosPosts::find()->where(['usuario_id' => $uId, 'post_id' => $pId])->one();
        // Si el usuario habia votado, retira el voto
        if ($voto) {
            $voto->delete();

            return $this->findModel($pId)->votos;
        }

        $voto = new VotosPosts([
            'post_id' => $pId,
            'usuario_id' => $uId
        ]);

        if (!$voto->save()) {
            return $this->findModel($pId)->votos;
        }
        return $this->findModel($pId)->votos;
    }
}

views/posts/_form.php
<?php

use kartik\select2\Select2;

use yii\bootstrap4\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Posts */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="posts-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'media')->hiddenInput()->label(false) ?>

    <?= $form->field($model, 'desarrollo')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'juego_id')->widget(Select2::className(), [
        'data' => $listaJuegos,
        'options' => ['placeholder' => 'Introduzca el juego del que trata el post'],
        'pluginOptions' => [
          'allowClear' => false,
        ],
      ])->label('Juego del post'); ?>

    <?= $form->field($model, 'usuario_id')->hiddenInput([
      'readonly' => true,
      'value' => Yii::$app->user->identity->id,
      ])->label(false);
      ?>

    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/posts/_search.php
<?php

use yii\bootstrap4\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\PostsSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="posts-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'titulo') ?>

    <?= $form->field($model, 'created_at') ?>

    <?= $form->field($model, 'media') ?>

    <?= $form->field($model, 'desarrollo') ?>

    <?php // echo $form->field($model, 'juego_id') ?>

    <?php // echo $form->field($model, 'usuario_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/posts/create.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Posts */

$this->title = 'Crear Post';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="posts-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'listaJuegos' => $listaJuegos
    ]) ?>

</div>

views/posts/index.php
<?php

use yii\bootstrap4\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\PostsSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Posts';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="posts-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Crear Posts', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'titulo',
            [
                'attribute' => 'juego.titulo',
                'format' => 'text',
                'label' => 'Juego',
                'contentOptions' => [
                    'itemscope' => true,
                    'itemtype' => 'https://schema.org/VideoGame',
                    'itemprop' => 'name'
                ]
            ],
            [
                'attribute' => 'usuario.nombre',
                'format' => 'raw',
                'label' => 'Usuario',
                'value' => function ($model) {
                    if (empty($model->usuario_id)) {
                        return '<span class="text-danger">Eliminado</span>';
                    }
                    return Html::encode($model->usuario->nombre);
                }
            ],
            'created_at:RelativeTime',
            // 'desarrollo:ntext',
            // 'media',

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {update} {delete}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        if (Yii::$app->user->isGuest || Yii::$app->user->id != $model->usuario->id) {
                            return '';
                        }
                        return Html::a('', ['update', 'id' => $model->id], [
                            'class' => 'glyphicon glyphicon-pencil',
                            'title' => 'Editar post',
                            'style' => [
                                'color' => 'red',
                            ],
                        ]);
                    },
                    'delete' => function ($url, $model, $key) {
                        if (Yii::$app->user->isGuest || Yii::$app->user->id != $model->usuario->id) {
                            return '';
                        }
                        return Html::a('', ['delete', 'id' => $model->id], [
                            'class' => 'glyphicon glyphicon-trash',
                            'title' => 'Borrar post',
                            'style' => [
                                'color' => 'red',
                            ],
                            'data' => [
                                'confirm' => 'Seguro que quieres borrar el post?',
                                'method' => 'POST',
                            ],
                        ]);
                    }
                ]
            ],
        ],
    ]); ?>


</div>

views/posts/update.php
<?php

use yii\bootstrap4\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Posts */

$this->title = 'Modificando post: ';
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="posts-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'listaJuegos' => $listaJuegos,
    ]) ?>

</div>

views/posts/view.php
<?php

use yii\grid\GridView;
use yii\bootstrap4\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this yii\web\View */
/* @var $model app\models\Posts */

$this->title = $model->titulo;
$this->params['breadcrumbs'][] = ['label' => 'Posts', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);

$url = Url::to(['posts/votar']);
$uId = Yii::$app->user->isGuest ? false : Yii::$app->user->id;
$pId = $model->id;

$js = <<<SCRIPT
$("#botonVoto").click(votar);
function votar(e){
  e.preventDefault();
  $.ajax({
    method: 'POST',
    url: '$url',
    data: {pId: $pId, uId: $uId},
    success: function(result){
      if (result) {
        $("#numeroVotos").html(result);
        cambiarIcono();
      } else {
        alert('Ha ocurrido un error al votar');
      }
    }
  });
}

function cambiarIcono(){
    var claseBoton = $("#botonVoto").attr('class');
    if (claseBoton == 'glyphicon glyphicon-star') {
        $("#botonVoto").attr('class', 'glyphicon glyphicon-star-empty');
    } else {
        $("#botonVoto").attr('class', 'glyphicon glyphicon-star');
    }
}
SCRIPT;
$this->registerJs($js);
?>
<div class="posts-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php if (!empty($model->usuario)) : ?>
        <?php if ($uId === $model->usuario->id) : ?>
        <p>
            <?= Html::a('Modificar', ['update', 'id' => $model->id], ['class' => 'btn btn-primary mr-2']) ?>
            <?= Html::a('Borrar', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => '¿Estas seguro de querer borrar este elemento?',
                'method' => 'post',
            ],
            ]) ?>
            </p>
        <?php endif ?>
    <?php endif ?>

    <h3>
        <?= Html::a('', 'javascript:void(0)', [
        'class' => $usuarioHaVotado ? 'glyphicon glyphicon-star' : 'glyphicon glyphicon-star-empty',
        'title' => 'Votar Post',
        'id' => 'botonVoto',
        ]) ?>
    </h3>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'desarrollo:ntext',
            'created_at:RelativeTime:Creado',
            [
              'attribute' => 'juego.titulo',
              'format' => 'text',
              'label' => 'Juego',
              'contentOptions' => [
                  'itemscope' => true,
                  'itemtype' => 'https://schema.org/VideoGame',
                  'itemprop' => 'name'
              ]
            ],
            [
                'attribute' => 'usuario.nombre:text:Usuario',
                'label' => 'Usuario',
                'format' => 'raw',
                'value' => function ($model) {
                    if (empty($model->usuario_id)) {
                        return '<span class="text-danger">Eliminado</span>';
                    }
                    return Html::encode($model->usuario->nombre);
                }
            ],
            [
                'attribute' => 'votos',
                'contentOptions' => [
                    'id' => 'numeroVotos',
                ]
            ]
        ],
    ]) ?>

<h2>Comentarios</h2>

<?php if (!Yii::$app->user->isGuest) {
    echo Html::a('Comentar', ['comentarios/create', 'pId' => $model->id], ['class' => 'btn btn-success mb-2']);
}?>
<?= GridView::widget([
        'dataProvider' => $comentariosProvider,
        'columns' => [
            [
                'attribute' => 'usuario.nombre',
                'format' => 'raw',
                'value' => function ($model) {
                    if (empty($model->usuario_id)) {
                        return '<span class="text-danger">Eliminado</span>';
                    }
                    return Html::encode($model->usuario->nombre);
                }
            ],
            'texto:text:Comentario',
            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{update} {delete} {reportar}',
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        if (empty($model->usuario)) {
                            return '';
                        }
                        if (Yii::$app->user->id != $model->usuario->id) {
                            return '';
                        }
                        return Html::a(
                            '<span class="glyphicon glyphicon-pencil"></span>',
                            [
                                '/comentarios/update',
                                'id' => $model->id,
                            ],
                            [
                                'title' => 'editar comentario',
                            ]
                        );
                    },
                    'delete' => function ($url, $model, $key) {
                        if (empty($model->usuario)) {
                            return '';
                        }
                        if (Yii::$app->user->id != $model->usuario->id) {
                            return '';
                        }
                        return Html::a(
                            '<span class="glyphicon glyphicon-trash"></span>',
                            [
                                'comentarios/delete',
                                'id' => $model->id,
                            ],
                            [
                                'data' => [
                                  'method' => 'post',
                                  'confirm' => '¿Estas seguro de borrar el comentario?(Esta accion no se puede deshacer)',
                                ],
                                'title' => 'borrar comentario',
                            ]
                        );
                    },
                    'reportar' => function ($url, $model, $action) {
                        if (Yii::$app->user->isGuest) {
                            return '';
                        };
                        
                        return Html::a('', ['comentarios/reportar', 'cId' => $model->id], [
                            'class' => 'glyphicon glyphicon-exclamation-sign',
                            'title' => 'Reportar comentario',
                            'style' => [
                                'color' => 'red',
                            ],
                            'data-confirm' => '¿Confirmas querer reportar el comentario?',
                        ]);
                    }
                ]
            ],
        ]
    ]); ?>

</div>